# Generated by Django 6.0.6 on 2026-07-04 18:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('college_name', models.CharField(max_length=150)),
                ('course_name', models.CharField(max_length=100)),
                ('internship_domain', models.CharField(max_length=100)),
                ('certificate_id', models.CharField(max_length=50, unique=True)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('issue_date', models.DateField()),
                ('completion_date', models.DateField()),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(default='Verified', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(max_length=50)),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('pdf', models.FileField(upload_to='certificates/')),
                ('issued_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verify.student')),
            ],
        ),
    ]
