# Generated by Django 6.0.6 on 2026-07-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='completion_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='certificate_id',
            new_name='internship_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='college_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='course_name',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='issue_date',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='student',
            name='internship_domain',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.AddField(
            model_name='student',
            name='certificate_1',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='student',
            name='certificate_2',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='student',
            name='qr_image',
            field=models.ImageField(blank=True, upload_to='qr/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
